In [1]:
import pandas as pd

In [2]:
Data = pd.read_csv('housing.csv')

In [3]:
Data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

# TASK1

In [4]:
A = Data[(Data['LotArea']>=6000)& (Data['LotConfig']=='Corner')]

In [5]:
A.reset_index()

,index,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
1,7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
2,9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000
3,14,15,20,RL,NaN,10920,Pave,NaN,IR1,Lvl,...,0,NaN,GdWo,NaN,0,5,2008,WD,Normal,157000
4,15,16,45,RM,51.0,6120,Pave,NaN,Reg,Lvl,...,0,NaN,GdPrv,NaN,0,7,2007,WD,Normal,132000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,1407,1408,20,RL,NaN,8780,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2009,WD,Normal,112000
237,1413,1414,20,RL,88.0,10994,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,9,2009,COD,Abnorml,257000
238,1420,1421,60,RL,90.0,11700,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,179900
239,1428,1429,30,RM,60.0,7200,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Abnorml,119000
240,1429,1430,20,RL,NaN,12546,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,4,2007,WD,Normal,182900

# TASK2

In [6]:
B= Data[(Data['BldgType'] =='1Fam') & (Data['HouseStyle'] =='1Story') & (Data['LandContour'] =='Lvl')]
B.reset_index()

,index,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
1,6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
2,10,11,20,RL,70.0,11200,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,129500
3,12,13,20,RL,NaN,12968,Pave,NaN,IR2,Lvl,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,144000
4,13,14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,8,2007,New,Partial,279500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1453,1454,20,RL,90.0,17217,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,7,2006,WD,Abnorml,84500
541,1454,1455,20,FV,62.0,7500,Pave,Pave,Reg,Lvl,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,185000
542,1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
543,1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
544,1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

# TASK3

In [7]:
C = Data[((Data['MSZoning']=='RH') | (Data['MSZoning']=='RM')) & (Data['BldgType']=='Twnhs')]
a=C.groupby('MSSubClass')['Id'].count()
print (a.idxmax(),": 1-STORY PUD (Planned Unit Development) - 1946 & NEWER} were the hot selling property in California") 
c= C[C['MSSubClass']==a.idxmax()]
c

160 : 1-STORY PUD (Planned Unit Development) - 1946 & NEWER} were the hot selling property in California

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
145,146,160,RM,24.0,2522,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,130000
193,194,160,RM,24.0,2522,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,130000
225,226,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,COD,Abnorml,112000
227,228,160,RM,21.0,1869,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,106000
232,233,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,94500
363,364,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,118000
430,431,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2008,COD,Abnorml,85400
500,501,160,RM,21.0,1890,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,113000
599,600,160,RM,24.0,1950,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,7,2008,COD,Normal,151000
655,656,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,3,2010,WD,Family,88000
837,838,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2008,WD,Normal,100000
915,916,160,RM,21.0,2001,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2007,WD,Normal,75000
1029,1030,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,118000
1038,1039,160,RM,21.0,1533,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,97000
1088,1089,160,RM,24.0,2522,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,137500
1219,1220,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,91500
1291,1292,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2009,WD,Normal,119500
1378,1379,160,RM,21.0,1953,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,83000

# TASK4

In [8]:

D= Data[(Data['BedroomAbvGr'] >=3) & (Data['TotalBsmtSF'] !=0)  & (Data['Exterior1st'] =='CemntBd') & (Data['Exterior2nd'] =='CmentBd')]
D.reset_index()

,index,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,23,24,120,RM,44.0,4224,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,129900
1,108,109,50,RM,85.0,8500,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,115000
2,196,197,20,RL,79.0,9416,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,9,2007,New,Partial,311872
3,261,262,60,RL,69.0,9588,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,11,2007,New,Partial,276000
4,278,279,20,RL,107.0,14450,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2007,New,Partial,415298
5,304,305,75,RM,87.0,18386,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,295000
6,305,306,20,RL,80.0,10386,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,7,2007,WD,Normal,305900
7,316,317,60,RL,94.0,13005,Pave,NaN,IR1,Lvl,...,0,NaN,GdPrv,NaN,0,8,2009,WD,Normal,260000
8,344,345,160,RM,36.0,2592,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,85000
9,349,350,60,RL,56.0,20431,Pave,NaN,IR2,Lvl,...,0,NaN,NaN,NaN,0,4,2006,New,Partial,437154
10,357,358,120,RM,44.0,4224,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,8,2007,WD,Normal,134000
11,377,378,60,FV,102.0,11143,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,12,2007,WD,Normal,340000
12,421,422,20,RL,NaN,16635,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,6,2009,WD,Normal,215000
13,490,491,160,RM,NaN,2665,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,115000
14,515,516,20,RL,94.0,12220,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,9,2009,New,Partial,402861
15,522,523,50,RM,50.0,5000,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,10,2006,WD,Normal,159000
16,523,524,60,RL,130.0,40094,Pave,NaN,IR1,Bnk,...,0,NaN,NaN,NaN,0,10,2007,New,Partial,184750
17,591,592,60,RL,97.0,13478,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,6,2009,ConLI,Normal,451950
18,618,619,20,RL,90.0,11694,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,7,2007,New,Partial,314813
19,650,651,60,FV,65.0,8125,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,205950
20,673,674,20,RL,110.0,14442,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,257500
21,724,725,20,RL,86.0,13286,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,2,2009,WD,Normal,320000
22,793,794,20,RL,76.0,9158,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2007,New,Partial,225000
23,817,818,20,RL,NaN,13265,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,7,2008,WD,Normal,271000
24,875,876,60,FV,75.0,9000,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,8,2007,New,Partial,303477
25,915,916,160,RM,21.0,2001,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,1,2007,WD,Normal,75000
26,973,974,20,FV,95.0,11639,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,12,2008,New,Partial,182000
27,980,981,85,RL,NaN,12122,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,7,2008,WD,Normal,178400
28,983,984,60,RL,NaN,11250,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,255900
29,994,995,20,RL,96.0,12456,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,337500
30,1007,1008,160,RM,21.0,2217,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,8,2009,WD,Normal,88000
31,1038,1039,160,RM,21.0,1533,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,97000
32,1046,1047,60,RL,85.0,16056,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,7,2006,New,Partial,556581
33,1068,1069,160,RM,42.0,3964,Pave,NaN,Reg,Lvl,...,0,NaN,GdPrv,NaN,0,6,2006,WD,Normal,151400
34,1086,1087,160,RM,NaN,1974,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,83500
35,1217,1218,20,FV,72.0,8640,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,9,2009,New,Partial,229456
36,1219,1220,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,91500
37,1291,1292,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,2,2009,WD,Normal,119500
38,1367,1368,160,RM,41.0,2665,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,127000
39,1374,1375,60,FV,85.0,10625,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,7,2008,WD,Normal,250000
40,1451,1452,20,RL,78.0,9262,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2009,New,Partial,287090
41,1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500

# TASK5

In [9]:
E= Data[(Data['GarageArea'] >=500 )]
E.reset_index()

,index,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
2,3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
3,4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
4,6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
630,1444,1445,20,RL,63.0,8500,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,179600
631,1447,1448,60,RL,80.0,10000,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,12,2007,WD,Normal,240000
632,1451,1452,20,RL,78.0,9262,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2009,New,Partial,287090
633,1452,1453,180,RM,35.0,3675,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,145000
634,1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000

In [10]:
import mysql.connector as sql

In [11]:
from sqlalchemy import create_engine

In [12]:
# Create SQLAlchemy engine to connect to MySQL Database
engine = create_engine("mysql+pymysql://{user}:{pw}@{host}/{db}"
.format(host='localhost', user='root',pw='mysql',db='challange'))

In [13]:
A.to_sql('task_one', engine, index=False) # employee details is the name of the table 
B.to_sql('task_two', engine, index=False) # employee details is the name of the table 
c.to_sql('task_three', engine, index=False) # employee details is the name of the table 
D.to_sql('task_four', engine, index=False) # employee details is the name of the table 
E.to_sql('task_five', engine, index=False) # employee details is the name of the table

635