# TASK1

In [1]:
import numpy as np

In [2]:
Emp_id_HR  = np.arange(1,501)
Emp_id_Fin = np.arange(501,1001)
Emp_id_IT = np.arange(1001,1501)
Emp_id_Sales = np.arange(1501,2001)


print('\n','Employee ID for HR','\n','\n',Emp_id_HR)
print('\n','Employee ID for Finanace','\n','\n',Emp_id_Fin)
print('\n','Employee ID for Sales','\n','\n',Emp_id_Sales)
print('\n','Employee ID for IT','\n','\n',Emp_id_IT)

 Employee ID for HR

 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252
 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270
 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306
 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324
 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342
 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360
 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378
 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396
 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414
 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432
 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450
 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468
 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486
 487 488 489 490 491 492 493 494 495 496 497 498 499 500]

 Employee ID for Finanace

 [ 501  502  503  504  505  506  507  508  509  510  511  512  513  514
  515  516  517  518  519  520  521  522  523  524  525  526  527  528
  529  530  531  532  533  534  535  536  537  538  539  540  541  542
  543  544  545  546  547  548  549  550  551  552  553  554  555  556
  557  558  559  560  561  562  563  564  565  566  567  568  569  570
  571  572  573  574  575  576  577  578  579  580  581  582  583  584
  585  586  587  588  589  590  591  592  593  594  595  596  597  598
  599  600  601  602  603  604  605  606  607  608  609  610  611  612
  613  614  615  616  617  618  619  620  621  622  623  624  625  626
  627  628  629  630  631  632  633  634  635  636  637  638  639  640
  641  642  643  644  645  646  647  648  649  650  651  652  653  654
  655  656  657  658  659  660  661  662  663  664  665  666  667  668
  669  670  671  672  673  674  675  676  677  678  679  680  681  682
  683  684  685  686  687  688  689  690  691  692  693  694  695  696
  697  698  699  700  701  702  703  704  705  706  707  708  709  710
  711  712  713  714  715  716  717  718  719  720  721  722  723  724
  725  726  727  728  729  730  731  732  733  734  735  736  737  738
  739  740  741  742  743  744  745  746  747  748  749  750  751  752
  753  754  755  756  757  758  759  760  761  762  763  764  765  766
  767  768  769  770  771  772  773  774  775  776  777  778  779  780
  781  782  783  784  785  786  787  788  789  790  791  792  793  794
  795  796  797  798  799  800  801  802  803  804  805  806  807  808
  809  810  811  812  813  814  815  816  817  818  819  820  821  822
  823  824  825  826  827  828  829  830  831  832  833  834  835  836
  837  838  839  840  841  842  843  844  845  846  847  848  849  850
  851  852  853  854  855  856  857  858  859  860  861  862  863  864
  865  866  867  868  869  870  871  872  873  874  875  876  877  878
  879  880  881  882  883  884  885  886  887  888  889  890  891  892
  893  894  895  896  897  898  899  900  901  902  903  904  905  906
  907  908  909  910  911  912  913  914  915  916  917  918  919  920
  921  922  923  924  925  926  927  928  929  930  931  932  933  934
  935  936  937  938  939  940  941  942  943  944  945  946  947  948
  949  950  951  952  953  954  955  956  957  958  959  960  961  962
  963  964  965  966  967  968  969  970  971  972  973  974  975  976
  977  978  979  980  981  982  983  984  985  986  987  988  989  990
  991  992  993  994  995  996  997  998  999 1000]

 Employee ID for Sales

 [1501 1502 1503 1504 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514
 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528
 1529 1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 1540 1541 1542
 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555 1556
 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570
 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580 1581 1582 1583 1584
 1585 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596 1597 1598
 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612
 1613 1614 1615 1616 1617 1618 1619 1620 1621 1622 1623 1624 1625 1626
 1627 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638 1639 1640
 1641 1642 1643 1644 1645 1646 1647 1648 1649 1650 1651 1652 1653 1654
 1655 1656 1657 1658 1659 1660 1661 1662 1663 1664 1665 1666 1667 1668
 1669 1670 1671 1672 1673 1674 1675 1676 1677 1678 1679 1680 1681 1682
 1683 1684 1685 1686 1687 1688 1689 1690 1691 1692 1693 1694 1695 1696
 1697 1698 1699 1700 1701 1702 1703 1704 1705 1706 1707 1708 1709 1710
 1711 1712 1713 1714 1715 1716 1717 1718 1719 1720 1721 1722 1723 1724
 1725 1726 1727 1728 1729 1730 1731 1732 1733 1734 1735 1736 1737 1738
 1739 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750 1751 1752
 1753 1754 1755 1756 1757 1758 1759 1760 1761 1762 1763 1764 1765 1766
 1767 1768 1769 1770 1771 1772 1773 1774 1775 1776 1777 1778 1779 1780
 1781 1782 1783 1784 1785 1786 1787 1788 1789 1790 1791 1792 1793 1794
 1795 1796 1797 1798 1799 1800 1801 1802 1803 1804 1805 1806 1807 1808
 1809 1810 1811 1812 1813 1814 1815 1816 1817 1818 1819 1820 1821 1822
 1823 1824 1825 1826 1827 1828 1829 1830 1831 1832 1833 1834 1835 1836
 1837 1838 1839 1840 1841 1842 1843 1844 1845 1846 1847 1848 1849 1850
 1851 1852 1853 1854 1855 1856 1857 1858 1859 1860 1861 1862 1863 1864
 1865 1866 1867 1868 1869 1870 1871 1872 1873 1874 1875 1876 1877 1878
 1879 1880 1881 1882 1883 1884 1885 1886 1887 1888 1889 1890 1891 1892
 1893 1894 1895 1896 1897 1898 1899 1900 1901 1902 1903 1904 1905 1906
 1907 1908 1909 1910 1911 1912 1913 1914 1915 1916 1917 1918 1919 1920
 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932 1933 1934
 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946 1947 1948
 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960 1961 1962
 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976
 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990
 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000]

 Employee ID for IT

 [1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028
 1029 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042
 1043 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056
 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070
 1071 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084
 1085 1086 1087 1088 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098
 1099 1100 1101 1102 1103 1104 1105 1106 1107 1108 1109 1110 1111 1112
 1113 1114 1115 1116 1117 1118 1119 1120 1121 1122 1123 1124 1125 1126
 1127 1128 1129 1130 1131 1132 1133 1134 1135 1136 1137 1138 1139 1140
 1141 1142 1143 1144 1145 1146 1147 1148 1149 1150 1151 1152 1153 1154
 1155 1156 1157 1158 1159 1160 1161 1162 1163 1164 1165 1166 1167 1168
 1169 1170 1171 1172 1173 1174 1175 1176 1177 1178 1179 1180 1181 1182
 1183 1184 1185 1186 1187 1188 1189 1190 1191 1192 1193 1194 1195 1196
 1197 1198 1199 1200 1201 1202 1203 1204 1205 1206 1207 1208 1209 1210
 1211 1212 1213 1214 1215 1216 1217 1218 1219 1220 1221 1222 1223 1224
 1225 1226 1227 1228 1229 1230 1231 1232 1233 1234 1235 1236 1237 1238
 1239 1240 1241 1242 1243 1244 1245 1246 1247 1248 1249 1250 1251 1252
 1253 1254 1255 1256 1257 1258 1259 1260 1261 1262 1263 1264 1265 1266
 1267 1268 1269 1270 1271 1272 1273 1274 1275 1276 1277 1278 1279 1280
 1281 1282 1283 1284 1285 1286 1287 1288 1289 1290 1291 1292 1293 1294
 1295 1296 1297 1298 1299 1300 1301 1302 1303 1304 1305 1306 1307 1308
 1309 1310 1311 1312 1313 1314 1315 1316 1317 1318 1319 1320 1321 1322
 1323 1324 1325 1326 1327 1328 1329 1330 1331 1332 1333 1334 1335 1336
 1337 1338 1339 1340 1341 1342 1343 1344 1345 1346 1347 1348 1349 1350
 1351 1352 1353 1354 1355 1356 1357 1358 1359 1360 1361 1362 1363 1364
 1365 1366 1367 1368 1369 1370 1371 1372 1373 1374 1375 1376 1377 1378
 1379 1380 1381 1382 1383 1384 1385 1386 1387 1388 1389 1390 1391 1392
 1393 1394 1395 1396 1397 1398 1399 1400 1401 1402 1403 1404 1405 1406
 1407 1408 1409 1410 1411 1412 1413 1414 1415 1416 1417 1418 1419 1420
 1421 1422 1423 1424 1425 1426 1427 1428 1429 1430 1431 1432 1433 1434
 1435 1436 1437 1438 1439 1440 1441 1442 1443 1444 1445 1446 1447 1448
 1449 1450 1451 1452 1453 1454 1455 1456 1457 1458 1459 1460 1461 1462
 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1473 1474 1475 1476
 1477 1478 1479 1480 1481 1482 1483 1484 1485 1486 1487 1488 1489 1490
 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500]

# TASK2

In [3]:
Sal_HR = np.random.randint(25000, 50000, 500)
Sal_Fin = Sal_HR*1.25
Sal_Sales =Sal_Fin/2
Sal_IT = Sal_HR+5000

print('\n','Salaries of HR','\n','\n',Sal_HR)
print('\n','Salaries of Finanace','\n','\n',Sal_Fin)
print('\n','Salaries of Sales','\n','\n',Sal_Sales)
print('\n','Salaries of IT','\n','\n',Sal_IT)

 Salaries of HR

 [32191 26064 44579 30105 41448 29737 43420 36071 46780 48890 27613 35858
 25393 41497 40750 33941 38953 34268 30757 27097 26655 42487 46609 39361
 37994 41784 31341 48815 34858 42317 44663 30369 29354 44282 26608 28723
 33758 45594 31687 40455 37991 39516 47667 48327 34999 42388 39773 38012
 42892 26084 43304 37253 37266 49610 34828 40182 25694 36229 45603 35951
 39735 42949 41689 34478 33460 41635 30126 45078 46571 34684 25194 47398
 37055 32771 34129 42009 36241 25940 29162 29797 30536 45791 35971 32917
 44038 28059 30085 42413 47571 36057 30193 26809 29506 32651 45486 27299
 36182 49650 36220 42087 35873 25825 36017 34620 32339 42704 33963 31919
 37757 44643 41394 46307 40824 30878 33222 33099 36892 46713 46902 37995
 26396 48680 28569 43321 49249 27946 45680 26962 28783 45491 31370 37551
 26457 30519 31260 39718 42513 35094 40832 37218 42332 33654 38529 27983
 35249 32129 31637 32228 30619 31581 44904 29065 46292 39616 33900 41253
 40493 26108 40528 26091 30328 42629 46947 40755 49141 39190 38760 25002
 41791 37921 34839 41215 42828 35917 49879 48787 49644 33772 49131 32889
 40461 44260 40121 45519 28889 41535 44124 49539 27253 45890 49470 44963
 40386 30060 26459 38165 47252 45378 43458 48193 36358 31710 37379 44941
 44278 43646 27910 35842 30837 26928 46249 28275 25985 29728 47273 32561
 36267 39134 42982 30081 46636 37157 46925 40873 32672 46144 40505 27950
 49131 32601 42295 34657 31687 27683 39285 44949 46255 27184 46525 27887
 46592 41239 39460 27372 26543 44584 27671 35647 40741 37331 29282 40004
 46208 30661 32656 45783 39937 41329 37796 30737 32455 34885 42135 28008
 34952 41036 40920 40421 44327 34839 40480 37995 33834 48440 49060 31528
 39287 38689 41697 26701 32750 48993 39215 35231 48357 32375 49114 36832
 40247 43022 48709 29288 45713 47974 43716 29664 26164 37386 48574 44069
 35807 38702 39030 40879 43964 38918 48739 46448 25650 25168 46890 42694
 30858 26816 31204 39828 36883 31152 36517 30044 42822 31251 25175 43728
 34790 33705 32964 36736 40175 40439 42365 28955 39143 37327 40208 32562
 40871 40130 44899 42201 44421 33755 31418 37443 35655 33901 25355 41266
 39219 26531 26781 28405 37745 40150 47711 44001 41276 35901 46070 49305
 37935 36820 49327 45420 33033 30905 25239 36193 37107 28520 45226 41115
 38340 35263 43609 40047 45720 39477 49836 31778 44050 41544 36256 39217
 30728 49085 38791 37768 29874 34602 30061 25405 35003 35127 38627 27534
 38356 45867 27493 38540 44655 29386 44590 46346 39081 29254 27383 27863
 30215 49466 46200 35158 35256 40095 42875 26132 48148 49923 35162 36089
 38928 42709 35188 27436 26628 26316 45419 46946 48635 32207 40134 35505
 43249 43393 29099 32942 45892 49636 45591 46959 49905 35426 46050 42196
 28633 42604 44439 46931 31615 43613 26670 27146 38640 31480 31824 36879
 35500 48420 48527 41412 31317 47666 49227 39080 36033 45466 47287 38835
 40406 41771 40685 39403 27699 31832 26006 27888 42249 47323 49449 48706
 48259 31289 46911 36468 38380 45507 41401 39825 30723 27783 25243 45030
 30871 48176 29648 41136 31674 44679 33201 49582]

 Salaries of Finanace

 [40238.75 32580.   55723.75 37631.25 51810.   37171.25 54275.   45088.75
 58475.   61112.5  34516.25 44822.5  31741.25 51871.25 50937.5  42426.25
 48691.25 42835.   38446.25 33871.25 33318.75 53108.75 58261.25 49201.25
 47492.5  52230.   39176.25 61018.75 43572.5  52896.25 55828.75 37961.25
 36692.5  55352.5  33260.   35903.75 42197.5  56992.5  39608.75 50568.75
 47488.75 49395.   59583.75 60408.75 43748.75 52985.   49716.25 47515.
 53615.   32605.   54130.   46566.25 46582.5  62012.5  43535.   50227.5
 32117.5  45286.25 57003.75 44938.75 49668.75 53686.25 52111.25 43097.5
 41825.   52043.75 37657.5  56347.5  58213.75 43355.   31492.5  59247.5
 46318.75 40963.75 42661.25 52511.25 45301.25 32425.   36452.5  37246.25
 38170.   57238.75 44963.75 41146.25 55047.5  35073.75 37606.25 53016.25
 59463.75 45071.25 37741.25 33511.25 36882.5  40813.75 56857.5  34123.75
 45227.5  62062.5  45275.   52608.75 44841.25 32281.25 45021.25 43275.
 40423.75 53380.   42453.75 39898.75 47196.25 55803.75 51742.5  57883.75
 51030.   38597.5  41527.5  41373.75 46115.   58391.25 58627.5  47493.75
 32995.   60850.   35711.25 54151.25 61561.25 34932.5  57100.   33702.5
 35978.75 56863.75 39212.5  46938.75 33071.25 38148.75 39075.   49647.5
 53141.25 43867.5  51040.   46522.5  52915.   42067.5  48161.25 34978.75
 44061.25 40161.25 39546.25 40285.   38273.75 39476.25 56130.   36331.25
 57865.   49520.   42375.   51566.25 50616.25 32635.   50660.   32613.75
 37910.   53286.25 58683.75 50943.75 61426.25 48987.5  48450.   31252.5
 52238.75 47401.25 43548.75 51518.75 53535.   44896.25 62348.75 60983.75
 62055.   42215.   61413.75 41111.25 50576.25 55325.   50151.25 56898.75
 36111.25 51918.75 55155.   61923.75 34066.25 57362.5  61837.5  56203.75
 50482.5  37575.   33073.75 47706.25 59065.   56722.5  54322.5  60241.25
 45447.5  39637.5  46723.75 56176.25 55347.5  54557.5  34887.5  44802.5
 38546.25 33660.   57811.25 35343.75 32481.25 37160.   59091.25 40701.25
 45333.75 48917.5  53727.5  37601.25 58295.   46446.25 58656.25 51091.25
 40840.   57680.   50631.25 34937.5  61413.75 40751.25 52868.75 43321.25
 39608.75 34603.75 49106.25 56186.25 57818.75 33980.   58156.25 34858.75
 58240.   51548.75 49325.   34215.   33178.75 55730.   34588.75 44558.75
 50926.25 46663.75 36602.5  50005.   57760.   38326.25 40820.   57228.75
 49921.25 51661.25 47245.   38421.25 40568.75 43606.25 52668.75 35010.
 43690.   51295.   51150.   50526.25 55408.75 43548.75 50600.   47493.75
 42292.5  60550.   61325.   39410.   49108.75 48361.25 52121.25 33376.25
 40937.5  61241.25 49018.75 44038.75 60446.25 40468.75 61392.5  46040.
 50308.75 53777.5  60886.25 36610.   57141.25 59967.5  54645.   37080.
 32705.   46732.5  60717.5  55086.25 44758.75 48377.5  48787.5  51098.75
 54955.   48647.5  60923.75 58060.   32062.5  31460.   58612.5  53367.5
 38572.5  33520.   39005.   49785.   46103.75 38940.   45646.25 37555.
 53527.5  39063.75 31468.75 54660.   43487.5  42131.25 41205.   45920.
 50218.75 50548.75 52956.25 36193.75 48928.75 46658.75 50260.   40702.5
 51088.75 50162.5  56123.75 52751.25 55526.25 42193.75 39272.5  46803.75
 44568.75 42376.25 31693.75 51582.5  49023.75 33163.75 33476.25 35506.25
 47181.25 50187.5  59638.75 55001.25 51595.   44876.25 57587.5  61631.25
 47418.75 46025.   61658.75 56775.   41291.25 38631.25 31548.75 45241.25
 46383.75 35650.   56532.5  51393.75 47925.   44078.75 54511.25 50058.75
 57150.   49346.25 62295.   39722.5  55062.5  51930.   45320.   49021.25
 38410.   61356.25 48488.75 47210.   37342.5  43252.5  37576.25 31756.25
 43753.75 43908.75 48283.75 34417.5  47945.   57333.75 34366.25 48175.
 55818.75 36732.5  55737.5  57932.5  48851.25 36567.5  34228.75 34828.75
 37768.75 61832.5  57750.   43947.5  44070.   50118.75 53593.75 32665.
 60185.   62403.75 43952.5  45111.25 48660.   53386.25 43985.   34295.
 33285.   32895.   56773.75 58682.5  60793.75 40258.75 50167.5  44381.25
 54061.25 54241.25 36373.75 41177.5  57365.   62045.   56988.75 58698.75
 62381.25 44282.5  57562.5  52745.   35791.25 53255.   55548.75 58663.75
 39518.75 54516.25 33337.5  33932.5  48300.   39350.   39780.   46098.75
 44375.   60525.   60658.75 51765.   39146.25 59582.5  61533.75 48850.
 45041.25 56832.5  59108.75 48543.75 50507.5  52213.75 50856.25 49253.75
 34623.75 39790.   32507.5  34860.   52811.25 59153.75 61811.25 60882.5
 60323.75 39111.25 58638.75 45585.   47975.   56883.75 51751.25 49781.25
 38403.75 34728.75 31553.75 56287.5  38588.75 60220.   37060.   51420.
 39592.5  55848.75 41501.25 61977.5 ]

 Salaries of Sales

 [20119.375 16290.    27861.875 18815.625 25905.    18585.625 27137.5
 22544.375 29237.5   30556.25  17258.125 22411.25  15870.625 25935.625
 25468.75  21213.125 24345.625 21417.5   19223.125 16935.625 16659.375
 26554.375 29130.625 24600.625 23746.25  26115.    19588.125 30509.375
 21786.25  26448.125 27914.375 18980.625 18346.25  27676.25  16630.
 17951.875 21098.75  28496.25  19804.375 25284.375 23744.375 24697.5
 29791.875 30204.375 21874.375 26492.5   24858.125 23757.5   26807.5
 16302.5   27065.    23283.125 23291.25  31006.25  21767.5   25113.75
 16058.75  22643.125 28501.875 22469.375 24834.375 26843.125 26055.625
 21548.75  20912.5   26021.875 18828.75  28173.75  29106.875 21677.5
 15746.25  29623.75  23159.375 20481.875 21330.625 26255.625 22650.625
 16212.5   18226.25  18623.125 19085.    28619.375 22481.875 20573.125
 27523.75  17536.875 18803.125 26508.125 29731.875 22535.625 18870.625
 16755.625 18441.25  20406.875 28428.75  17061.875 22613.75  31031.25
 22637.5   26304.375 22420.625 16140.625 22510.625 21637.5   20211.875
 26690.    21226.875 19949.375 23598.125 27901.875 25871.25  28941.875
 25515.    19298.75  20763.75  20686.875 23057.5   29195.625 29313.75
 23746.875 16497.5   30425.    17855.625 27075.625 30780.625 17466.25
 28550.    16851.25  17989.375 28431.875 19606.25  23469.375 16535.625
 19074.375 19537.5   24823.75  26570.625 21933.75  25520.    23261.25
 26457.5   21033.75  24080.625 17489.375 22030.625 20080.625 19773.125
 20142.5   19136.875 19738.125 28065.    18165.625 28932.5   24760.
 21187.5   25783.125 25308.125 16317.5   25330.    16306.875 18955.
 26643.125 29341.875 25471.875 30713.125 24493.75  24225.    15626.25
 26119.375 23700.625 21774.375 25759.375 26767.5   22448.125 31174.375
 30491.875 31027.5   21107.5   30706.875 20555.625 25288.125 27662.5
 25075.625 28449.375 18055.625 25959.375 27577.5   30961.875 17033.125
 28681.25  30918.75  28101.875 25241.25  18787.5   16536.875 23853.125
 29532.5   28361.25  27161.25  30120.625 22723.75  19818.75  23361.875
 28088.125 27673.75  27278.75  17443.75  22401.25  19273.125 16830.
 28905.625 17671.875 16240.625 18580.    29545.625 20350.625 22666.875
 24458.75  26863.75  18800.625 29147.5   23223.125 29328.125 25545.625
 20420.    28840.    25315.625 17468.75  30706.875 20375.625 26434.375
 21660.625 19804.375 17301.875 24553.125 28093.125 28909.375 16990.
 29078.125 17429.375 29120.    25774.375 24662.5   17107.5   16589.375
 27865.    17294.375 22279.375 25463.125 23331.875 18301.25  25002.5
 28880.    19163.125 20410.    28614.375 24960.625 25830.625 23622.5
 19210.625 20284.375 21803.125 26334.375 17505.    21845.    25647.5
 25575.    25263.125 27704.375 21774.375 25300.    23746.875 21146.25
 30275.    30662.5   19705.    24554.375 24180.625 26060.625 16688.125
 20468.75  30620.625 24509.375 22019.375 30223.125 20234.375 30696.25
 23020.    25154.375 26888.75  30443.125 18305.    28570.625 29983.75
 27322.5   18540.    16352.5   23366.25  30358.75  27543.125 22379.375
 24188.75  24393.75  25549.375 27477.5   24323.75  30461.875 29030.
 16031.25  15730.    29306.25  26683.75  19286.25  16760.    19502.5
 24892.5   23051.875 19470.    22823.125 18777.5   26763.75  19531.875
 15734.375 27330.    21743.75  21065.625 20602.5   22960.    25109.375
 25274.375 26478.125 18096.875 24464.375 23329.375 25130.    20351.25
 25544.375 25081.25  28061.875 26375.625 27763.125 21096.875 19636.25
 23401.875 22284.375 21188.125 15846.875 25791.25  24511.875 16581.875
 16738.125 17753.125 23590.625 25093.75  29819.375 27500.625 25797.5
 22438.125 28793.75  30815.625 23709.375 23012.5   30829.375 28387.5
 20645.625 19315.625 15774.375 22620.625 23191.875 17825.    28266.25
 25696.875 23962.5   22039.375 27255.625 25029.375 28575.    24673.125
 31147.5   19861.25  27531.25  25965.    22660.    24510.625 19205.
 30678.125 24244.375 23605.    18671.25  21626.25  18788.125 15878.125
 21876.875 21954.375 24141.875 17208.75  23972.5   28666.875 17183.125
 24087.5   27909.375 18366.25  27868.75  28966.25  24425.625 18283.75
 17114.375 17414.375 18884.375 30916.25  28875.    21973.75  22035.
 25059.375 26796.875 16332.5   30092.5   31201.875 21976.25  22555.625
 24330.    26693.125 21992.5   17147.5   16642.5   16447.5   28386.875
 29341.25  30396.875 20129.375 25083.75  22190.625 27030.625 27120.625
 18186.875 20588.75  28682.5   31022.5   28494.375 29349.375 31190.625
 22141.25  28781.25  26372.5   17895.625 26627.5   27774.375 29331.875
 19759.375 27258.125 16668.75  16966.25  24150.    19675.    19890.
 23049.375 22187.5   30262.5   30329.375 25882.5   19573.125 29791.25
 30766.875 24425.    22520.625 28416.25  29554.375 24271.875 25253.75
 26106.875 25428.125 24626.875 17311.875 19895.    16253.75  17430.
 26405.625 29576.875 30905.625 30441.25  30161.875 19555.625 29319.375
 22792.5   23987.5   28441.875 25875.625 24890.625 19201.875 17364.375
 15776.875 28143.75  19294.375 30110.    18530.    25710.    19796.25
 27924.375 20750.625 30988.75 ]

 Salaries of IT

 [37191 31064 49579 35105 46448 34737 48420 41071 51780 53890 32613 40858
 30393 46497 45750 38941 43953 39268 35757 32097 31655 47487 51609 44361
 42994 46784 36341 53815 39858 47317 49663 35369 34354 49282 31608 33723
 38758 50594 36687 45455 42991 44516 52667 53327 39999 47388 44773 43012
 47892 31084 48304 42253 42266 54610 39828 45182 30694 41229 50603 40951
 44735 47949 46689 39478 38460 46635 35126 50078 51571 39684 30194 52398
 42055 37771 39129 47009 41241 30940 34162 34797 35536 50791 40971 37917
 49038 33059 35085 47413 52571 41057 35193 31809 34506 37651 50486 32299
 41182 54650 41220 47087 40873 30825 41017 39620 37339 47704 38963 36919
 42757 49643 46394 51307 45824 35878 38222 38099 41892 51713 51902 42995
 31396 53680 33569 48321 54249 32946 50680 31962 33783 50491 36370 42551
 31457 35519 36260 44718 47513 40094 45832 42218 47332 38654 43529 32983
 40249 37129 36637 37228 35619 36581 49904 34065 51292 44616 38900 46253
 45493 31108 45528 31091 35328 47629 51947 45755 54141 44190 43760 30002
 46791 42921 39839 46215 47828 40917 54879 53787 54644 38772 54131 37889
 45461 49260 45121 50519 33889 46535 49124 54539 32253 50890 54470 49963
 45386 35060 31459 43165 52252 50378 48458 53193 41358 36710 42379 49941
 49278 48646 32910 40842 35837 31928 51249 33275 30985 34728 52273 37561
 41267 44134 47982 35081 51636 42157 51925 45873 37672 51144 45505 32950
 54131 37601 47295 39657 36687 32683 44285 49949 51255 32184 51525 32887
 51592 46239 44460 32372 31543 49584 32671 40647 45741 42331 34282 45004
 51208 35661 37656 50783 44937 46329 42796 35737 37455 39885 47135 33008
 39952 46036 45920 45421 49327 39839 45480 42995 38834 53440 54060 36528
 44287 43689 46697 31701 37750 53993 44215 40231 53357 37375 54114 41832
 45247 48022 53709 34288 50713 52974 48716 34664 31164 42386 53574 49069
 40807 43702 44030 45879 48964 43918 53739 51448 30650 30168 51890 47694
 35858 31816 36204 44828 41883 36152 41517 35044 47822 36251 30175 48728
 39790 38705 37964 41736 45175 45439 47365 33955 44143 42327 45208 37562
 45871 45130 49899 47201 49421 38755 36418 42443 40655 38901 30355 46266
 44219 31531 31781 33405 42745 45150 52711 49001 46276 40901 51070 54305
 42935 41820 54327 50420 38033 35905 30239 41193 42107 33520 50226 46115
 43340 40263 48609 45047 50720 44477 54836 36778 49050 46544 41256 44217
 35728 54085 43791 42768 34874 39602 35061 30405 40003 40127 43627 32534
 43356 50867 32493 43540 49655 34386 49590 51346 44081 34254 32383 32863
 35215 54466 51200 40158 40256 45095 47875 31132 53148 54923 40162 41089
 43928 47709 40188 32436 31628 31316 50419 51946 53635 37207 45134 40505
 48249 48393 34099 37942 50892 54636 50591 51959 54905 40426 51050 47196
 33633 47604 49439 51931 36615 48613 31670 32146 43640 36480 36824 41879
 40500 53420 53527 46412 36317 52666 54227 44080 41033 50466 52287 43835
 45406 46771 45685 44403 32699 36832 31006 32888 47249 52323 54449 53706
 53259 36289 51911 41468 43380 50507 46401 44825 35723 32783 30243 50030
 35871 53176 34648 46136 36674 49679 38201 54582]

# TASK3

In [4]:
Total_cst_HR = sum(Sal_HR)
Total_cst_Fin = sum(Sal_Fin)
Total_cst_Sales = sum(Sal_Sales)
Total_cst_IT = sum(Sal_IT)

print('\n','Total Cost of HR:',Total_cst_HR)
print('\n','Total Cost of Finanace:',Total_cst_Fin)
print('\n','Total Cost of Sales:',Total_cst_Sales)
print('\n','Total Cost of IT:',Total_cst_IT)

print('\n','\n',"Department with maximax cost is Finanace Department which is: ",max(Total_cst_HR,Total_cst_Fin,Total_cst_Sales,Total_cst_IT) )

 Total Cost of HR: 18930660

 Total Cost of Finanace: 23663325.0

 Total Cost of Sales: 11831662.5

 Total Cost of IT: 21430660


 Department with maximax cost is Finanace Department which is:  23663325.0

# TASK4

In [5]:
Highest_Sal_HR = np.sort(Sal_HR)[::-1]
Highest_Sal_Fin = np.sort(Sal_Fin)[::-1]
print('\n','Top 10 Salries of HR','\n','\n', Highest_Sal_Fin[0:10])
print('\n','Top 10 Salries of Finance','\n','\n', Highest_Sal_HR[0:10])

 Top 10 Salries of HR

 [62403.75 62381.25 62348.75 62295.   62062.5  62055.   62045.   62012.5
 61977.5  61923.75]

 Top 10 Salries of Finance

 [49923 49905 49879 49836 49650 49644 49636 49610 49582 49539]

# TASK5

In [6]:
#To get the employees whose salary is greater then 45k

In [7]:
Sales_index = np.where(Sal_Sales > 45000)

In [8]:
Sales_SALARY = Sal_Sales[Sales_index] # there is no employee in sales department whose salary is greater then 45000

In [9]:
IT_index = np.where(Sal_IT > 45000)

In [10]:
print('Salaries of IT department greater then 45000 i.e',np.size(IT_index),'employees','\n','\n',Sal_IT[IT_index])

Salaries of IT department greater then 45000 i.e 214 employees

 [49579 46448 48420 51780 53890 46497 45750 47487 51609 46784 53815 47317
 49663 49282 50594 45455 52667 53327 47388 47892 48304 54610 45182 50603
 47949 46689 46635 50078 51571 52398 47009 50791 49038 47413 52571 50486
 54650 47087 47704 49643 46394 51307 45824 51713 51902 53680 48321 54249
 50680 50491 47513 45832 47332 49904 51292 46253 45493 45528 47629 51947
 45755 54141 46791 46215 47828 54879 53787 54644 54131 45461 49260 45121
 50519 46535 49124 54539 50890 54470 49963 45386 52252 50378 48458 53193
 49941 49278 48646 51249 52273 47982 51636 51925 45873 51144 45505 54131
 47295 49949 51255 51525 51592 46239 49584 45741 45004 51208 50783 46329
 47135 46036 45920 45421 49327 45480 53440 54060 46697 53993 53357 54114
 45247 48022 53709 50713 52974 48716 53574 49069 45879 48964 53739 51448
 51890 47694 47822 48728 45175 45439 47365 45208 45871 45130 49899 47201
 49421 46266 45150 52711 49001 46276 51070 54305 54327 50420 50226 46115
 48609 45047 50720 54836 49050 46544 54085 50867 49655 49590 51346 54466
 51200 45095 47875 53148 54923 47709 50419 51946 53635 45134 48249 48393
 50892 54636 50591 51959 54905 51050 47196 47604 49439 51931 48613 53420
 53527 46412 52666 54227 50466 52287 45406 46771 45685 47249 52323 54449
 53706 53259 51911 50507 46401 50030 53176 46136 49679 54582]

# TASK6

In [11]:
Sales_index_Low = np.where(Sal_Sales < 45000)

In [12]:
Sales_SALARY = Sal_Sales[Sales_index_Low]

In [13]:
Updated_Sales_Sal = Sales_SALARY*1.1

In [14]:
print('\n','Salaries of sales Department increased by 10% whose salary is less then 45000', '\n', '\n',Updated_Sales_Sal)

 Salaries of sales Department increased by 10% whose salary is less then 45000

 [22131.3125 17919.     30648.0625 20697.1875 28495.5    20444.1875
 29851.25   24798.8125 32161.25   33611.875  18983.9375 24652.375
 17457.6875 28529.1875 28015.625  23334.4375 26780.1875 23559.25
 21145.4375 18629.1875 18325.3125 29209.8125 32043.6875 27060.6875
 26120.875  28726.5    21546.9375 33560.3125 23964.875  29092.9375
 30705.8125 20878.6875 20180.875  30443.875  18293.     19747.0625
 23208.625  31345.875  21784.8125 27812.8125 26118.8125 27167.25
 32771.0625 33224.8125 24061.8125 29141.75   27343.9375 26133.25
 29488.25   17932.75   29771.5    25611.4375 25620.375  34106.875
 23944.25   27625.125  17664.625  24907.4375 31352.0625 24716.3125
 27317.8125 29527.4375 28661.1875 23703.625  23003.75   28624.0625
 20711.625  30991.125  32017.5625 23845.25   17320.875  32586.125
 25475.3125 22530.0625 23463.6875 28881.1875 24915.6875 17833.75
 20048.875  20485.4375 20993.5    31481.3125 24730.0625 22630.4375
 30276.125  19290.5625 20683.4375 29158.9375 32705.0625 24789.1875
 20757.6875 18431.1875 20285.375  22447.5625 31271.625  18768.0625
 24875.125  34134.375  24901.25   28934.8125 24662.6875 17754.6875
 24761.6875 23801.25   22233.0625 29359.     23349.5625 21944.3125
 25957.9375 30692.0625 28458.375  31836.0625 28066.5    21228.625
 22840.125  22755.5625 25363.25   32115.1875 32245.125  26121.5625
 18147.25   33467.5    19641.1875 29783.1875 33858.6875 19212.875
 31405.     18536.375  19788.3125 31275.0625 21566.875  25816.3125
 18189.1875 20981.8125 21491.25   27306.125  29227.6875 24127.125
 28072.     25587.375  29103.25   23137.125  26488.6875 19238.3125
 24233.6875 22088.6875 21750.4375 22156.75   21050.5625 21711.9375
 30871.5    19982.1875 31825.75   27236.     23306.25   28361.4375
 27838.9375 17949.25   27863.     17937.5625 20850.5    29307.4375
 32276.0625 28019.0625 33784.4375 26943.125  26647.5    17188.875
 28731.3125 26070.6875 23951.8125 28335.3125 29444.25   24692.9375
 34291.8125 33541.0625 34130.25   23218.25   33777.5625 22611.1875
 27816.9375 30428.75   27583.1875 31294.3125 19861.1875 28555.3125
 30335.25   34058.0625 18736.4375 31549.375  34010.625  30912.0625
 27765.375  20666.25   18190.5625 26238.4375 32485.75   31197.375
 29877.375  33132.6875 24996.125  21800.625  25698.0625 30896.9375
 30441.125  30006.625  19188.125  24641.375  21200.4375 18513.
 31796.1875 19439.0625 17864.6875 20438.     32500.1875 22385.6875
 24933.5625 26904.625  29550.125  20680.6875 32062.25   25545.4375
 32260.9375 28100.1875 22462.     31724.     27847.1875 19215.625
 33777.5625 22413.1875 29077.8125 23826.6875 21784.8125 19032.0625
 27008.4375 30902.4375 31800.3125 18689.     31985.9375 19172.3125
 32032.     28351.8125 27128.75   18818.25   18248.3125 30651.5
 19023.8125 24507.3125 28009.4375 25665.0625 20131.375  27502.75
 31768.     21079.4375 22451.     31475.8125 27456.6875 28413.6875
 25984.75   21131.6875 22312.8125 23983.4375 28967.8125 19255.5
 24029.5    28212.25   28132.5    27789.4375 30474.8125 23951.8125
 27830.     26121.5625 23260.875  33302.5    33728.75   21675.5
 27009.8125 26598.6875 28666.6875 18356.9375 22515.625  33682.6875
 26960.3125 24221.3125 33245.4375 22257.8125 33765.875  25322.
 27669.8125 29577.625  33487.4375 20135.5    31427.6875 32982.125
 30054.75   20394.     17987.75   25702.875  33394.625  30297.4375
 24617.3125 26607.625  26833.125  28104.3125 30225.25   26756.125
 33508.0625 31933.     17634.375  17303.     32236.875  29352.125
 21214.875  18436.     21452.75   27381.75   25357.0625 21417.
 25105.4375 20655.25   29440.125  21485.0625 17307.8125 30063.
 23918.125  23172.1875 22662.75   25256.     27620.3125 27801.8125
 29125.9375 19906.5625 26910.8125 25662.3125 27643.     22386.375
 28098.8125 27589.375  30868.0625 29013.1875 30539.4375 23206.5625
 21599.875  25742.0625 24512.8125 23306.9375 17431.5625 28370.375
 26963.0625 18240.0625 18411.9375 19528.4375 25949.6875 27603.125
 32801.3125 30250.6875 28377.25   24681.9375 31673.125  33897.1875
 26080.3125 25313.75   33912.3125 31226.25   22710.1875 21247.1875
 17351.8125 24882.6875 25511.0625 19607.5    31092.875  28266.5625
 26358.75   24243.3125 29981.1875 27532.3125 31432.5    27140.4375
 34262.25   21847.375  30284.375  28561.5    24926.     26961.6875
 21125.5    33745.9375 26668.8125 25965.5    20538.375  23788.875
 20666.9375 17465.9375 24064.5625 24149.8125 26556.0625 18929.625
 26369.75   31533.5625 18901.4375 26496.25   30700.3125 20202.875
 30655.625  31862.875  26868.1875 20112.125  18825.8125 19155.8125
 20772.8125 34007.875  31762.5    24171.125  24238.5    27565.3125
 29476.5625 17965.75   33101.75   34322.0625 24173.875  24811.1875
 26763.     29362.4375 24191.75   18862.25   18306.75   18092.25
 31225.5625 32275.375  33436.5625 22142.3125 27592.125  24409.6875
 29733.6875 29832.6875 20005.5625 22647.625  31550.75   34124.75
 31343.8125 32284.3125 34309.6875 24355.375  31659.375  29009.75
 19685.1875 29290.25   30551.8125 32265.0625 21735.3125 29983.9375
 18335.625  18662.875  26565.     21642.5    21879.     25354.3125
 24406.25   33288.75   33362.3125 28470.75   21530.4375 32770.375
 33843.5625 26867.5    24772.6875 31257.875  32509.8125 26699.0625
 27779.125  28717.5625 27970.9375 27089.5625 19043.0625 21884.5
 17879.125  19173.     29046.1875 32534.5625 33996.1875 33485.375
 33178.0625 21511.1875 32251.3125 25071.75   26386.25   31286.0625
 28463.1875 27379.6875 21122.0625 19100.8125 17354.5625 30958.125
 21223.8125 33121.     20383.     28281.     21775.875  30716.8125
 22825.6875 34087.625 ]

Importing Data from CSV File

In [15]:
Data = np.genfromtxt("DS1_C4_S1_AdmissionPredict_Data_Practice.csv",delimiter=',',skip_header=1)
GRE = Data[:,1]
TOFEL = Data[:,2]
Research = Data[:,7]

# TASK1

In [16]:

print("Number of students whose GRE Score is greater then 320 is:",np.size(np.where(GRE> 320)) )

Number of students whose GRE Score is greater then 320 is: 163

# TASK2

In [19]:
Chance_of_Admit=Data[:,8]
index_tofel = np.where(TOFEL> 110)
a = TOFEL[index_tofel]
b = Chance_of_Admit[index_tofel]
c=np.array([a,b])
c.T
print('\n','Chance of admit whose tofel is above 110', '\n','\n',c.T)

 Chance of admit whose tofel is above 110

 [[118.     0.92]
 [115.     0.9 ]
 [111.     0.84]
 [112.     0.78]
 [114.     0.7 ]
 [116.     0.94]
 [119.     0.95]
 [119.     0.97]
 [120.     0.94]
 [118.     0.91]
 [114.     0.9 ]
 [112.     0.94]
 [117.     0.87]
 [113.     0.91]
 [114.     0.86]
 [119.     0.89]
 [111.     0.78]
 [116.     0.78]
 [112.     0.72]
 [111.     0.52]
 [112.     0.55]
 [114.     0.61]
 [115.     0.78]
 [118.     0.94]
 [112.     0.96]
 [111.     0.93]
 [114.     0.72]
 [112.     0.74]
 [120.     0.96]
 [115.     0.92]
 [115.     0.94]
 [120.     0.86]
 [119.     0.9 ]
 [113.     0.79]
 [112.     0.74]
 [111.     0.87]
 [117.     0.91]
 [116.     0.93]
 [117.     0.94]
 [119.     0.94]
 [113.     0.85]
 [112.     0.78]
 [112.     0.84]
 [118.     0.92]
 [114.     0.96]
 [112.     0.79]
 [113.     0.89]
 [116.     0.8 ]
 [118.     0.9 ]
 [115.     0.92]
 [120.     0.97]
 [112.     0.8 ]
 [113.     0.81]
 [114.     0.83]
 [116.     0.96]
 [114.     0.93]
 [116.     0.94]
 [112.     0.86]
 [111.     0.81]
 [117.     0.89]
 [113.     0.89]
 [111.     0.87]
 [111.     0.85]
 [119.     0.9 ]
 [113.     0.89]
 [118.     0.93]
 [115.     0.93]
 [112.     0.88]
 [111.     0.9 ]
 [114.     0.86]
 [118.     0.94]
 [120.     0.97]
 [120.     0.97]
 [120.     0.95]
 [119.     0.96]
 [117.     0.94]
 [116.     0.93]
 [112.     0.91]
 [113.     0.76]
 [112.     0.71]
 [111.     0.82]
 [113.     0.91]
 [111.     0.88]
 [112.     0.85]
 [114.     0.86]
 [115.     0.7 ]
 [114.     0.76]
 [111.     0.77]
 [115.     0.93]
 [114.     0.85]
 [119.     0.9 ]
 [111.     0.7 ]
 [113.     0.83]
 [113.     0.89]
 [111.     0.8 ]
 [112.     0.94]
 [116.     0.93]
 [118.     0.92]
 [114.     0.89]
 [120.     0.86]
 [114.     0.9 ]
 [112.     0.71]
 [112.     0.8 ]
 [111.     0.79]
 [113.     0.8 ]
 [116.     0.81]
 [112.     0.8 ]
 [113.     0.8 ]
 [111.     0.83]
 [118.     0.94]
 [116.     0.93]
 [115.     0.91]
 [114.     0.86]
 [119.     0.95]
 [113.     0.96]
 [117.     0.96]
 [112.     0.84]
 [111.     0.89]
 [116.     0.91]
 [117.     0.95]]

# TASK3

In [18]:
Serial_No = Data[:,0]
index = np.where((TOFEL> 115)&(GRE>315)& (Research==1))
A=Serial_No[index]
B=np.size(Serial_No[index])
print('\n',"Serial Number of student eligible for Scholarship",'\n', '\n', A)
print('\n', '\n',"There are", B , 'Students eligible for scholarship')

 Serial Number of student eligible for Scholarship

 [  1.  23.  24.  25.  26.  33.  53.  71.  82.  98.  99. 108. 109. 121.
 122. 130. 139. 142. 144. 149. 152. 172. 177. 188. 194. 203. 204. 213.
 214. 215. 216. 260. 286. 287. 326. 338. 362. 373. 386. 398. 400.]


 There are 41 Students eligible for scholarship